version: '3.7'
services:
  proxy:
    container_name: Reverse_Proxy
    image: techwise-technologies/proxy:${PROXY_VERSION}
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: unless-stopped
    networks:
      - proxy-tier

  letsencrypt-companion:
    container_name: Lets_Encrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    restart: unless-stopped 
    networks:
      - proxy-tier
  
  nginx:
    container_name: Web_Server
    image: techwise-technologies/nginx:${NGINX_VERSION}
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - nextcloud:/var/www/html:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - nextcloud
    networks:
      - proxy-tier
      - default
    
  protonmail:
    container_name: Mail_Server
    image: techwise-technologies/proton-bridge:${PROTON_BRIDGE_VERSION}
    build:
      context: .
      dockerfile: ./proton-bridge/Dockerfile
    volumes:
      - protonmail:/root 
    expose: 
      - "25/tcp"
      - "143/tcp" 
    restart: unless-stopped 
  
  nextcloud:
    container_name: Nextcloud
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
    depends_on:
      - db
      - redis
      - protonmail
    restart: unless-stopped 

  redis:
    container_name: DB_Cache
    image: redis:${REDIS_VERSION}
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    volumes:
      - ${REDIS_CONF}:/etc/redis/redis.conf
      - ${REDIS_VAR_LIB}:/var/lib/redis
      - ${REDIS_DATA_DIR}:/data
    environment:
     - REDIS_REPLICATION_MODE=master
    restart: unless-stopped

  db:
    container_name: DB
    image: mariadb:${MARIADB_VERSION}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped

  cron:
    container_name: Cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:
  protonmail: 

networks:
  proxy-tier:
